---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-lab
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: kafeventconsumer-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true