# Default values for kafeventconsumer
# This file contains the base configuration
# Override these in apps/local-rancher/kafeventconsumer-values.yaml
---
replicaCount: 1
image:
  repository: jittakal/image-kafeventconsumer
  tag: "1.0.0"