# Default values for kafeventproducer
# This file contains the base configuration
# Override these in apps/local-rancher/kafeventproducer-values.yaml
---
replicaCount: 1
image:
  repository: jittakal/image-kafeventproducer
  tag: "1.0.0"