{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafeventstore.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafeventstore.labels" . | nindent 4 }}
  {{- $annotations := include "kafeventstore.serviceAccountAnnotations" . | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
