apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafeventproducer.fullname" . }}-secret
  labels:
    {{- include "kafeventproducer.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_SASL_USERNAME: {{ .Values.kafka.security.sasl.username | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.kafka.security.sasl.password | quote }}
