---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafeventproducer
  namespace: kafka-producers
spec:
  values:
    global:
      namespace: kafka-producers
    replicaCount: 1
    image:
      repository: jittakal/image-kafeventproducer
      tag: "1.0.0"
    kafka:
      brokers:
        - "kafka-kraft-hs.kafka.svc.cluster.local:9093"