---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafeventproducer
  namespace: kafka-producers
spec:
  values:
    replicaCount: 1
    image:
      repository: jittakal/kafeventproducer
      tag: "1.0.0"
    kafka:
      brokers:
        - "kafka-kraft-hs.kafka.svc.cluster.local:9093"