---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafeventconsumer
  namespace: kafka-consumers
spec:
  values:
    replicaCount: 0
    image:
      repository: jittakal/kafeventconsumer
      tag: "1.0.0"
    kafka:
      brokers:
        - "kafka-kraft-hs.kafka.svc.cluster.local:9093"