---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-lab
resources:
  - ../base/kafeventconsumer
  - ../base/kafeventproducer
configMapGenerator:
  - name: kafeventconsumer-values
    behavior: merge
    files:
      - values.yaml=kafeventconsumer-values.yaml
  - name: kafeventproducer-values
    behavior: merge
    files:
      - values.yaml=kafeventproducer-values.yaml
generatorOptions:
  disableNameSuffixHash: true