---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/kafeventconsumer
  - ../base/kafeventproducer
patches:
  - path: kafeventconsumer-values.yaml
    target:
      kind: HelmRelease
      name: kafeventconsumer
  - path: kafeventproducer-values.yaml
    target:
      kind: HelmRelease
      name: kafeventproducer